name: Python checks

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

permissions: read-all

jobs:
  lint:
    uses: bmos/bmos/.github/workflows/python-lint.yml@main
    permissions:
      contents: write
      security-events: write
